//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PET.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int Id { get; set; }
        public int ObservantId { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Observant Observant { get; set; }
    }
}
